version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=production
      - OLLAMA_URL=http://host.docker.internal:11434
  
  frontend:
    build: .
    ports:
      - "5173:80"
    depends_on:
      - backend
